"""Shared static detector configuration blocks."""

from __future__ import annotations

from .affect import (
    CELEBRATION_GRATITUDE,
    CELEBRATION_PROGRESS,
    CELEBRATION_RELIEF,
    CELEBRATION_WIN,
)
from .meaning import MISALIGNMENT_SIGNALS
from .patterns import (
    AVOIDANCE_SIGNALS,
    BYPASS_ACCOUNTABILITY,
    BYPASS_DISMISS,
    EXTERNAL_REPEAT_SIGNALS,
    GENUINE_INTEGRATION,
    OVERTHINKING_SIGNALS,
    PEOPLE_PLEASING_SIGNALS,
    PERFECTIONISM_SIGNALS,
    PREMATURE_ACCEPTANCE,
    SPIRITUAL_INFLATION,
    WITHDRAWAL_SIGNALS,
)
from .safety import (
    CRISIS_TIER1,
    CRISIS_TIER2,
    DECISION_SEEKING,
    DEPENDENCY_KEYWORDS,
    GRANDIOSITY_SIGNALS,
    HIGH_DEPENDENCY_THRESHOLD,
    ISOLATION_SIGNALS,
    MODERATE_DEPENDENCY_THRESHOLD,
)

__all__ = [
    "AVOIDANCE_SIGNALS",
    "BYPASS_ACCOUNTABILITY",
    "BYPASS_DISMISS",
    "CELEBRATION_GRATITUDE",
    "CELEBRATION_PROGRESS",
    "CELEBRATION_RELIEF",
    "CELEBRATION_WIN",
    "CRISIS_TIER1",
    "CRISIS_TIER2",
    "DECISION_SEEKING",
    "DEPENDENCY_KEYWORDS",
    "EXTERNAL_REPEAT_SIGNALS",
    "GENUINE_INTEGRATION",
    "GRANDIOSITY_SIGNALS",
    "HIGH_DEPENDENCY_THRESHOLD",
    "ISOLATION_SIGNALS",
    "MISALIGNMENT_SIGNALS",
    "MODERATE_DEPENDENCY_THRESHOLD",
    "OVERTHINKING_SIGNALS",
    "PEOPLE_PLEASING_SIGNALS",
    "PERFECTIONISM_SIGNALS",
    "PREMATURE_ACCEPTANCE",
    "SPIRITUAL_INFLATION",
    "WITHDRAWAL_SIGNALS",
]
