"""Shared static detector configuration blocks."""

from __future__ import annotations

from .meaning import MISALIGNMENT_SIGNALS
from .safety import (
    CRISIS_TIER1,
    CRISIS_TIER2,
    DECISION_SEEKING,
    DEPENDENCY_KEYWORDS,
    GRANDIOSITY_SIGNALS,
    HIGH_DEPENDENCY_THRESHOLD,
    ISOLATION_SIGNALS,
    MODERATE_DEPENDENCY_THRESHOLD,
)

__all__ = [
    "CRISIS_TIER1",
    "CRISIS_TIER2",
    "DECISION_SEEKING",
    "DEPENDENCY_KEYWORDS",
    "GRANDIOSITY_SIGNALS",
    "HIGH_DEPENDENCY_THRESHOLD",
    "ISOLATION_SIGNALS",
    "MISALIGNMENT_SIGNALS",
    "MODERATE_DEPENDENCY_THRESHOLD",
]
