"""Static config for affect, intensity, grief, and somatic detectors."""

from __future__ import annotations

CELEBRATION_WIN: tuple[str, ...] = (
    "i finally did it",
    "i did it",
    "i finally said it",
    "i said it",
    "i got the job",
    "we made it",
    "i got through it",
    "i passed",
    "i finished",
    "i completed",
    "i succeeded",
    "i made it",
    "i pulled it off",
    "it worked",
    "it actually worked",
    "we did it",
    "i got in",
    "i got accepted",
    "i got promoted",
)

CELEBRATION_RELIEF: tuple[str, ...] = (
    "i can breathe again",
    "feel lighter",
    "feeling lighter",
    "i feel lighter",
    "the worst is over",
    "it's finally over",
    "it's over",
    "that's behind me",
    "i made it through",
    "survived it",
    "i survived",
    "relief",
    "such a relief",
    "what a relief",
    "huge weight lifted",
    "weight off my chest",
    "weight off my shoulders",
    "i feel free",
    "feel free",
    "finally free",
)

CELEBRATION_GRATITUDE: tuple[str, ...] = (
    "i'm so grateful",
    "i am so grateful",
    "so grateful",
    "i feel grateful",
    "feeling grateful",
    "i want to say thank you",
    "i'm thankful",
    "i am thankful",
    "something shifted and i feel it",
    "something shifted",
    "deep gratitude",
    "full of gratitude",
)

CELEBRATION_PROGRESS: tuple[str, ...] = (
    "i noticed i didn't react",
    "i noticed i did not react",
    "i caught myself this time",
    "i caught myself",
    "i noticed myself",
    "i didn't do the thing",
    "i did not do the thing",
    "i didn't spiral",
    "i did not spiral",
    "i held it together",
    "i didn't shut down",
    "i did not shut down",
    "i stayed",
    "i spoke up",
    "i said no",
    "i set the boundary",
    "something is different this time",
    "something feels different",
    "not the same as before",
    "i didn't go back",
    "i did not go back",
    "i chose differently",
    "i responded differently",
)
