"""Static config for affect, intensity, grief, and somatic detectors."""

from __future__ import annotations

ACTIVE_ANGER: tuple[str, ...] = (
    "i'm so angry",
    "i am so angry",
    "i'm furious",
    "i'm livid",
    "i'm so frustrated",
    "makes me furious",
    "makes me so angry",
    "i could scream",
    "i want to scream",
    "i want to explode",
    "i'm fed up",
    "i'm sick of this",
    "i'm sick of them",
    "i'm enraged",
    "i'm seething",
    "boiling inside",
    "how dare they",
    "how dare he",
    "how dare she",
    "this is so unfair",
    "it's not fair",
    "this isn't right",
    "i hate this",
    "i hate them",
    "i hate him",
    "i hate her",
    "i'm so done",
    "i can't stand it",
    "i can't take it anymore",
    "i'm disgusted",
    "i'm outraged",
)

SELF_ANGER: tuple[str, ...] = (
    "i'm so angry at myself",
    "i'm furious at myself",
    "i hate myself",
    "i'm disgusted with myself",
    "i can't believe i did that",
    "how could i be so stupid",
    "i'm so disappointed in myself",
)

RESIDUAL_ANGER: tuple[str, ...] = (
    "still so angry about",
    "can't let go of the anger",
    "the anger won't go away",
    "i keep getting angry about",
    "every time i think about it i get angry",
    "i've been angry for",
    "been holding this anger",
    "the resentment",
    "bitter about",
    "i resent",
)

ACUTE_GRIEF: tuple[str, ...] = (
    "they died",
    "he died",
    "she died",
    "my mother died",
    "my father died",
    "my partner died",
    "my friend died",
    "my dog died",
    "my cat died",
    "passed away",
    "just lost",
    "just found out",
    "died yesterday",
    "died last week",
    "died this morning",
    "died three days ago",
    "died last month",
    "died last year",
    "funeral",
    "grief",
    "grieving",
    "mourning",
    "bereavement",
    "can't believe they're gone",
    "cannot believe they are gone",
    "cannot believe she is gone",
    "cannot believe he is gone",
    "they're gone",
    "she's gone",
    "he's gone",
    "she is gone",
    "he is gone",
    "they are gone",
    "miss them so much",
    "miss her so much",
    "miss him so much",
    "losing my mind without",
    "nothing without them",
    "the worst pain i've ever",
    "don't know how to do this",
    "doesn't feel real",
    "still cannot believe",
    "can't accept it",
    "still in shock",
)

ANTICIPATORY_GRIEF: tuple[str, ...] = (
    "watching them decline",
    "watching my father decline",
    "watching my mother decline",
    "watching my partner decline",
    "every day feels like goodbye",
    "every day is another goodbye",
    "every day is a goodbye",
    "saying goodbye every day",
    "feels like saying goodbye every day",
    "losing her a little more every day",
    "losing him a little more every day",
    "losing them a little more every day",
    "already mourning them",
    "losing them before they're gone",
    "terminal diagnosis",
    "they don't have long",
    "they do not have long",
    "running out of time",
    "saying goodbye slowly",
    "caregiving",
    "hospice",
    "watching them disappear",
    "not the same person anymore",
    "months of goodbye",
    "watching someone fade",
)

AMBIGUOUS_LOSS: tuple[str, ...] = (
    "no one understands why i'm upset",
    "not allowed to be this sad",
    "it's not like they died",
    "no one sees this as a real loss",
    "disenfranchised grief",
    "end of a friendship",
    "lost a friend",
    "estrangement",
    "estranged",
    "miscarriage",
    "pregnancy loss",
    "lost my sense of self",
    "lost who i was",
    "don't know if i'm allowed to grieve",
    "the relationship ended but no one understands why it hurts this much",
)

COMPLICATED_GRIEF: tuple[str, ...] = (
    "feel guilty that i feel relieved",
    "relieved they're gone",
    "loved them and they hurt me",
    "grieving someone who hurt me",
    "complicated feelings about their death",
    "don't know how to grieve",
    "angry at them for dying",
    "angry that they left",
    "toxic relationship",
    "abusive",
    "mixed feelings about losing them",
    "love and hate at the same time",
)

CELEBRATION_WIN: tuple[str, ...] = (
    "i finally did it",
    "i did it",
    "i finally said it",
    "i said it",
    "i got the job",
    "we made it",
    "i got through it",
    "i passed",
    "i finished",
    "i completed",
    "i succeeded",
    "i made it",
    "i pulled it off",
    "it worked",
    "it actually worked",
    "we did it",
    "i got in",
    "i got accepted",
    "i got promoted",
)

CELEBRATION_RELIEF: tuple[str, ...] = (
    "i can breathe again",
    "feel lighter",
    "feeling lighter",
    "i feel lighter",
    "the worst is over",
    "it's finally over",
    "it's over",
    "that's behind me",
    "i made it through",
    "survived it",
    "i survived",
    "relief",
    "such a relief",
    "what a relief",
    "huge weight lifted",
    "weight off my chest",
    "weight off my shoulders",
    "i feel free",
    "feel free",
    "finally free",
)

CELEBRATION_GRATITUDE: tuple[str, ...] = (
    "i'm so grateful",
    "i am so grateful",
    "so grateful",
    "i feel grateful",
    "feeling grateful",
    "i want to say thank you",
    "i'm thankful",
    "i am thankful",
    "something shifted and i feel it",
    "something shifted",
    "deep gratitude",
    "full of gratitude",
)

CELEBRATION_PROGRESS: tuple[str, ...] = (
    "i noticed i didn't react",
    "i noticed i did not react",
    "i caught myself this time",
    "i caught myself",
    "i noticed myself",
    "i didn't do the thing",
    "i did not do the thing",
    "i didn't spiral",
    "i did not spiral",
    "i held it together",
    "i didn't shut down",
    "i did not shut down",
    "i stayed",
    "i spoke up",
    "i said no",
    "i set the boundary",
    "something is different this time",
    "something feels different",
    "not the same as before",
    "i didn't go back",
    "i did not go back",
    "i chose differently",
    "i responded differently",
)
