"""Static config for direction, existential, insight, and parts detectors."""

from __future__ import annotations

LOSTNESS_SIGNALS: tuple[str, ...] = (
    "i feel lost",
    "i'm lost",
    "feel so lost",
    "feeling lost",
    "feel completely lost",
    "completely lost",
    "i feel completely lost",
    "so lost right now",
    "don't know what i want",
    "do not know what i want",
    "don't know what to do with my life",
    "do not know what to do with my life",
    "don't know where i'm going",
    "do not know what direction",
    "no idea what direction",
    "no idea what i want",
    "have no direction",
    "no sense of direction",
    "lost my direction",
    "don't know who i am anymore",
    "do not know who i am",
    "lost myself",
    "don't recognize myself",
    "don't know what matters to me",
    "do not know what matters",
    "not sure what i'm doing with my life",
    "what am i doing with my life",
    "what's the point",
    "is this all there is",
    "have no idea where i am going",
    "no idea where my life is going",
)

MEANING_SIGNALS: tuple[str, ...] = (
    "no purpose",
    "feel purposeless",
    "lost my purpose",
    "no sense of purpose",
    "nothing feels meaningful",
    "nothing matters",
    "what's the meaning",
    "feel empty",
    "feel hollow",
    "going through the motions",
    "just existing",
    "not really living",
    "feel like a robot",
    "life feels flat",
    "life feels pointless",
    "no passion",
    "lost my passion",
    "nothing excites me",
    "nothing interests me",
    "bored with everything",
    "bored with my life",
)

SHOULD_SIGNALS: tuple[str, ...] = (
    "should want this but i don't",
    "supposed to want",
    "supposed to be happy",
    "have everything i wanted but",
    "achieved my goals but",
    "reached my goal but",
    "got what i worked for but",
    "should feel satisfied but",
    "should feel happy but",
    "feels like it's not mine",
    "living someone else's life",
    "living the life other people want me to live",
    "living someone else's dream",
    "don't know if this is really what i want",
    "is this even what i want",
    "following someone else's script",
    "doing what was expected",
    "never questioned it before",
    "just followed the path",
    "achieved everything i was supposed to",
    "have achieved everything",
    "i have achieved everything",
    "achieved everything and feel",
    "feel completely empty",
    "feel empty after",
    "everything looks right from the outside",
    "looks right from outside but",
)

COMPARISON_SIGNALS: tuple[str, ...] = (
    "everyone else seems to know",
    "everyone else has it figured out",
    "everyone else knows what they're doing",
    "everyone else has direction",
    "why can't i figure it out",
    "why don't i have it together",
    "behind everyone else",
    "falling behind",
    "not where i should be",
    "compare myself to",
    "compared to others",
)

TRANSITION_SIGNALS: tuple[str, ...] = (
    "at a crossroads",
    "don't know which way to go",
    "big decision",
    "life transition",
    "major change",
    "starting over",
    "reinventing myself",
    "chapter ending",
    "new chapter",
    "midlife",
    "quarter life",
    "don't know what's next",
    "what comes next",
    "what now",
    "reassessing everything",
    "questioning everything",
    "reevaluating",
)

MISALIGNMENT_SIGNALS: tuple[str, ...] = (
    "feels off",
    "something feels wrong",
    "something feels missing",
    "not aligned",
    "out of alignment",
    "feels inauthentic",
    "not being true to myself",
    "compromising myself",
    "selling out",
    "not living my values",
    "acting against my values",
    "not who i want to be",
    "not the person i wanted to become",
    "drifted from what matters",
    "lost track of what matters",
)

IDENTITY_SHIFT: tuple[str, ...] = (
    "don't recognize myself",
    "i don't recognize myself anymore",
    "i do not recognize myself",
    "i do not recognize myself anymore",
    "i dont recognize myself",
    "i've lost myself",
    "i'm losing myself",
    "who am i anymore",
    "who am i now",
    "i don't know who i am",
    "i do not know who i am",
    "i used to know who i was",
    "between versions of myself",
    "not the same person",
    "i'm not who i thought i was",
    "the person i used to be",
    "something fundamental has changed",
    "i feel like a stranger to myself",
    "feel like a stranger in my own life",
    "stranger in my own life",
    "stranger to myself",
    "my sense of self",
    "identity feels unstable",
    "i don't know what i stand for anymore",
    "i do not know what i stand for",
    "i've outgrown who i was",
    "the old me is gone",
    "i am not the same person",
    "lost my sense of who i am",
)

MEANING_DEPTH: tuple[str, ...] = (
    "whether any of this means anything at all",
    "what's the point of anything",
    "what is the point of all this",
    "what is the point of any of this",
    "why does any of this matter",
    "why any of this matters",
    "does any of this matter",
    "what are we here for",
    "why are we here",
    "why am i here",
    "what is the meaning of life",
    "what does it all mean",
    "nothing means anything",
    "meaning doesn't exist",
    "i keep asking why and",
    "keep asking why",
    "there is no answer to why",
    "even when things are good there's",
    "underneath everything there's",
    "this hollow feeling",
    "underlying emptiness",
    "a kind of emptiness that won't go away",
    "am i supposed to feel more than this",
    "should feel more than this",
    "why does nothing feel like enough",
    "nothing feels like enough",
    "silence where meaning should be",
    "just silence",
)

ENDINGS_GRIEF: tuple[str, ...] = (
    "a chapter is ending",
    "chapter of my life is ending",
    "chapter is closing",
    "era is ending",
    "this era of my life",
    "this phase is over",
    "grieving who i was",
    "grieving the life i thought i'd have",
    "grieving a future",
    "mourning what could have been",
    "something is dying",
    "letting go of who i was",
    "wasn't supposed to end this way",
    "it was supposed to mean more",
    "this should have meant more",
    "it's over and i can't",
    "already started to move on but",
    "can't fully take it in",
)

LARGER_QUESTIONS: tuple[str, ...] = (
    "what happens when we die",
    "what happens after death",
    "fear of death",
    "aware that i'm going to die",
    "aware that this is all temporary",
    "nothing lasts",
    "everything ends",
    "impermanence",
    "smallness in the face of",
    "the scale of everything",
    "how small i am",
    "how insignificant",
    "my life is so brief",
    "time is passing so fast",
    "weight of time",
    "i won't be here forever",
    "the universe doesn't care",
    "there is no inherent meaning",
    "nothing matters cosmically",
    "existence feels arbitrary",
)

HOLDING_QUESTIONS: tuple[str, ...] = (
    "i keep asking myself",
    "i've been sitting with this question",
    "a question i can't shake",
    "this question keeps returning",
    "i don't expect an answer but",
    "i don't know if there's an answer",
    "maybe there is no answer",
    "just sitting with",
    "i'm not looking for a solution",
    "i'm not asking you to fix this",
)

EXPLICIT_CONFLICT: tuple[str, ...] = (
    "part of me wants",
    "part of me knows",
    "part of me thinks",
    "part of me feels",
    "part of me is",
    "part of me says",
    "part of me hopes",
    "part of me believes",
    "part of me needs",
    "but another part",
    "but part of me",
    "but then part of me",
    "one part of me",
    "one side of me",
    "one voice says",
    "i want to but i",
    "i want to but part",
    "i know i should but",
    "i know i shouldn't but",
    "i keep telling myself but",
    "i tell myself but then",
    "my head says",
    "my heart says",
    "my gut says",
    "i want to stay but",
    "i want to leave but",
    "i want to try but",
    "i want to stop but",
)

SELF_DIALOGUE: tuple[str, ...] = (
    "i keep telling myself",
    "i tell myself",
    "i say to myself",
    "i remind myself",
    "i know better but",
    "i know this but",
    "i fight with myself",
    "i argue with myself",
    "i'm at war with myself",
    "i'm fighting myself",
    "torn between",
    "i'm torn",
    "can't decide",
    "going back and forth",
    "pulled in two directions",
    "don't know which part to listen to",
    "don't know which voice",
)

PART_NAMING: tuple[str, ...] = (
    "a part of me",
    "that part of me",
    "this part of me",
    "the part that",
    "the part of me that",
    "a side of me",
    "the side that",
    "a voice in me",
    "a voice that says",
    "something in me says",
    "something in me wants",
    "something in me won't",
    "something in me keeps",
)

BEHAVIORAL_CONFUSION: tuple[str, ...] = (
    "i don't understand why i",
    "don't know why i did",
    "i surprised myself",
    "i don't recognize myself",
    "that's not like me",
    "i acted against my own values",
    "i did the opposite of what i wanted",
    "i don't know what i want",
    "i'm confusing myself",
    "i contradict myself",
    "i'm exhausted from fighting myself",
    "tired of fighting myself",
    "at war with myself",
    "battling myself",
)

EXPLICIT_INSIGHT: tuple[str, ...] = (
    "i finally understand",
    "i finally see",
    "i finally realize",
    "i finally get it",
    "i finally know why",
    "i now understand",
    "i now see",
    "i now realize",
    "oh  -  that's",
    "oh that's why",
    "oh i see",
    "i just realized",
    "i just understood",
    "i just saw",
    "it just clicked",
    "something clicked",
    "it all makes sense",
    "i never saw it before but",
    "i never understood but now",
    "that's what's been happening",
    "that's what i've been doing",
    "i can see now that",
    "i can see clearly now",
    "i understand now",
    "i get it now",
    "i see it now",
    "this is why i",
    "that's why i always",
    "that's why i keep",
    "i've been doing this my whole",
    "i've been doing this for years",
)

EMERGING_INSIGHT: tuple[str, ...] = (
    "i'm starting to see",
    "i'm beginning to understand",
    "i think i see",
    "i think i understand now",
    "maybe that's why",
    "i wonder if that's why",
    "it's becoming clearer",
    "something is becoming clear",
    "i'm starting to connect",
    "i can see the connection",
    "it makes more sense now",
    "it's starting to make sense",
    "i hadn't thought of it that way",
    "i never thought of it like that",
    "that reframes everything",
    "that changes how i see",
    "i think i've been",
    "i'm realizing that i",
)

SELF_APPLICATION: tuple[str, ...] = (
    "that's my pattern",
    "that's the pattern",
    "i see the pattern",
    "i do this with",
    "i do this when",
    "i always do this when",
    "this is what i do",
    "this is what happens when i",
    "i recognize this",
    "i recognize that in myself",
    "that's exactly what happened",
    "i can see how i",
    "so that's where it comes from",
    "so that's why i",
    "it goes back to",
    "it comes from when",
)

POST_REFLECTION: tuple[str, ...] = (
    "yes that's it",
    "yes exactly",
    "that's exactly right",
    "that resonates",
    "that lands",
    "that hits different",
    "that's so true",
    "i feel that",
    "that's so accurate",
    "wow yes",
    "oh wow",
    "that's it",
    "yes that's",
    "exactly what i never dared to say out loud",
    "you're right",
    "that makes so much sense",
)
