"""Static config for direction, existential, insight, and parts detectors."""

from __future__ import annotations

MISALIGNMENT_SIGNALS: tuple[str, ...] = (
    "feels off",
    "something feels wrong",
    "something feels missing",
    "not aligned",
    "out of alignment",
    "feels inauthentic",
    "not being true to myself",
    "compromising myself",
    "selling out",
    "not living my values",
    "acting against my values",
    "not who i want to be",
    "not the person i wanted to become",
    "drifted from what matters",
    "lost track of what matters",
)

IDENTITY_SHIFT: tuple[str, ...] = (
    "don't recognize myself",
    "i don't recognize myself anymore",
    "i do not recognize myself",
    "i do not recognize myself anymore",
    "i dont recognize myself",
    "i've lost myself",
    "i'm losing myself",
    "who am i anymore",
    "who am i now",
    "i don't know who i am",
    "i do not know who i am",
    "i used to know who i was",
    "between versions of myself",
    "not the same person",
    "i'm not who i thought i was",
    "the person i used to be",
    "something fundamental has changed",
    "i feel like a stranger to myself",
    "feel like a stranger in my own life",
    "stranger in my own life",
    "stranger to myself",
    "my sense of self",
    "identity feels unstable",
    "i don't know what i stand for anymore",
    "i do not know what i stand for",
    "i've outgrown who i was",
    "the old me is gone",
    "i am not the same person",
    "lost my sense of who i am",
)

MEANING_DEPTH: tuple[str, ...] = (
    "whether any of this means anything at all",
    "what's the point of anything",
    "what is the point of all this",
    "what is the point of any of this",
    "why does any of this matter",
    "why any of this matters",
    "does any of this matter",
    "what are we here for",
    "why are we here",
    "why am i here",
    "what is the meaning of life",
    "what does it all mean",
    "nothing means anything",
    "meaning doesn't exist",
    "i keep asking why and",
    "keep asking why",
    "there is no answer to why",
    "even when things are good there's",
    "underneath everything there's",
    "this hollow feeling",
    "underlying emptiness",
    "a kind of emptiness that won't go away",
    "am i supposed to feel more than this",
    "should feel more than this",
    "why does nothing feel like enough",
    "nothing feels like enough",
    "silence where meaning should be",
    "just silence",
)

ENDINGS_GRIEF: tuple[str, ...] = (
    "a chapter is ending",
    "chapter of my life is ending",
    "chapter is closing",
    "era is ending",
    "this era of my life",
    "this phase is over",
    "grieving who i was",
    "grieving the life i thought i'd have",
    "grieving a future",
    "mourning what could have been",
    "something is dying",
    "letting go of who i was",
    "wasn't supposed to end this way",
    "it was supposed to mean more",
    "this should have meant more",
    "it's over and i can't",
    "already started to move on but",
    "can't fully take it in",
)

LARGER_QUESTIONS: tuple[str, ...] = (
    "what happens when we die",
    "what happens after death",
    "fear of death",
    "aware that i'm going to die",
    "aware that this is all temporary",
    "nothing lasts",
    "everything ends",
    "impermanence",
    "smallness in the face of",
    "the scale of everything",
    "how small i am",
    "how insignificant",
    "my life is so brief",
    "time is passing so fast",
    "weight of time",
    "i won't be here forever",
    "the universe doesn't care",
    "there is no inherent meaning",
    "nothing matters cosmically",
    "existence feels arbitrary",
)

HOLDING_QUESTIONS: tuple[str, ...] = (
    "i keep asking myself",
    "i've been sitting with this question",
    "a question i can't shake",
    "this question keeps returning",
    "i don't expect an answer but",
    "i don't know if there's an answer",
    "maybe there is no answer",
    "just sitting with",
    "i'm not looking for a solution",
    "i'm not asking you to fix this",
)

EXPLICIT_INSIGHT: tuple[str, ...] = (
    "i finally understand",
    "i finally see",
    "i finally realize",
    "i finally get it",
    "i finally know why",
    "i now understand",
    "i now see",
    "i now realize",
    "oh  -  that's",
    "oh that's why",
    "oh i see",
    "i just realized",
    "i just understood",
    "i just saw",
    "it just clicked",
    "something clicked",
    "it all makes sense",
    "i never saw it before but",
    "i never understood but now",
    "that's what's been happening",
    "that's what i've been doing",
    "i can see now that",
    "i can see clearly now",
    "i understand now",
    "i get it now",
    "i see it now",
    "this is why i",
    "that's why i always",
    "that's why i keep",
    "i've been doing this my whole",
    "i've been doing this for years",
)

EMERGING_INSIGHT: tuple[str, ...] = (
    "i'm starting to see",
    "i'm beginning to understand",
    "i think i see",
    "i think i understand now",
    "maybe that's why",
    "i wonder if that's why",
    "it's becoming clearer",
    "something is becoming clear",
    "i'm starting to connect",
    "i can see the connection",
    "it makes more sense now",
    "it's starting to make sense",
    "i hadn't thought of it that way",
    "i never thought of it like that",
    "that reframes everything",
    "that changes how i see",
    "i think i've been",
    "i'm realizing that i",
)

SELF_APPLICATION: tuple[str, ...] = (
    "that's my pattern",
    "that's the pattern",
    "i see the pattern",
    "i do this with",
    "i do this when",
    "i always do this when",
    "this is what i do",
    "this is what happens when i",
    "i recognize this",
    "i recognize that in myself",
    "that's exactly what happened",
    "i can see how i",
    "so that's where it comes from",
    "so that's why i",
    "it goes back to",
    "it comes from when",
)

POST_REFLECTION: tuple[str, ...] = (
    "yes that's it",
    "yes exactly",
    "that's exactly right",
    "that resonates",
    "that lands",
    "that hits different",
    "that's so true",
    "i feel that",
    "that's so accurate",
    "wow yes",
    "oh wow",
    "that's it",
    "yes that's",
    "exactly what i never dared to say out loud",
    "you're right",
    "that makes so much sense",
)
