"""Static config for direction, existential, insight, and parts detectors."""

from __future__ import annotations

MISALIGNMENT_SIGNALS: tuple[str, ...] = (
    "feels off",
    "something feels wrong",
    "something feels missing",
    "not aligned",
    "out of alignment",
    "feels inauthentic",
    "not being true to myself",
    "compromising myself",
    "selling out",
    "not living my values",
    "acting against my values",
    "not who i want to be",
    "not the person i wanted to become",
    "drifted from what matters",
    "lost track of what matters",
)

EXPLICIT_INSIGHT: tuple[str, ...] = (
    "i finally understand",
    "i finally see",
    "i finally realize",
    "i finally get it",
    "i finally know why",
    "i now understand",
    "i now see",
    "i now realize",
    "oh  -  that's",
    "oh that's why",
    "oh i see",
    "i just realized",
    "i just understood",
    "i just saw",
    "it just clicked",
    "something clicked",
    "it all makes sense",
    "i never saw it before but",
    "i never understood but now",
    "that's what's been happening",
    "that's what i've been doing",
    "i can see now that",
    "i can see clearly now",
    "i understand now",
    "i get it now",
    "i see it now",
    "this is why i",
    "that's why i always",
    "that's why i keep",
    "i've been doing this my whole",
    "i've been doing this for years",
)

EMERGING_INSIGHT: tuple[str, ...] = (
    "i'm starting to see",
    "i'm beginning to understand",
    "i think i see",
    "i think i understand now",
    "maybe that's why",
    "i wonder if that's why",
    "it's becoming clearer",
    "something is becoming clear",
    "i'm starting to connect",
    "i can see the connection",
    "it makes more sense now",
    "it's starting to make sense",
    "i hadn't thought of it that way",
    "i never thought of it like that",
    "that reframes everything",
    "that changes how i see",
    "i think i've been",
    "i'm realizing that i",
)

SELF_APPLICATION: tuple[str, ...] = (
    "that's my pattern",
    "that's the pattern",
    "i see the pattern",
    "i do this with",
    "i do this when",
    "i always do this when",
    "this is what i do",
    "this is what happens when i",
    "i recognize this",
    "i recognize that in myself",
    "that's exactly what happened",
    "i can see how i",
    "so that's where it comes from",
    "so that's why i",
    "it goes back to",
    "it comes from when",
)

POST_REFLECTION: tuple[str, ...] = (
    "yes that's it",
    "yes exactly",
    "that's exactly right",
    "that resonates",
    "that lands",
    "that hits different",
    "that's so true",
    "i feel that",
    "that's so accurate",
    "wow yes",
    "oh wow",
    "that's it",
    "yes that's",
    "exactly what i never dared to say out loud",
    "you're right",
    "that makes so much sense",
)
