"""Static config for spiritual bypass and shadow-pattern detectors."""

from __future__ import annotations

BYPASS_DISMISS: tuple[str, ...] = (
    "everything happens for a reason",
    "it was meant to be",
    "the universe has a plan",
    "this is my karma",
    "i'm meant to learn from this",
    "it's all happening for my highest good",
    "i just need to let go",
    "i need to surrender",
    "i need to accept it",
    "i shouldn't be attached",
    "i need to raise my vibration",
    "this is just an ego reaction",
    "i need to transcend this",
    "at a soul level i chose this",
    "my higher self knows why",
    "i'm being tested",
    "this is a lesson i needed",
    "everything is perfect as it is",
    "i just need to be grateful",
)

PREMATURE_ACCEPTANCE: tuple[str, ...] = (
    "i've already forgiven them",
    "i'm at peace with it",
    "i've moved on",
    "i'm over it now",
    "i've accepted it",
    "i'm grateful for the lesson",
    "it made me stronger",
    "everything worked out for the best",
    "i'm not angry anymore",
    "i've released it",
)

SPIRITUAL_INFLATION: tuple[str, ...] = (
    "as a lightworker",
    "as an empath i feel",
    "i'm highly sensitive so",
    "my vibration is too high for",
    "i've ascended past",
    "from a 5d perspective",
    "i've done the work",
    "i'm very spiritually advanced",
    "most people can't understand",
    "i operate at a different level",
)

BYPASS_ACCOUNTABILITY: tuple[str, ...] = (
    "it was their karma not mine",
    "they were my teacher",
    "i called this into my life",
    "i manifested this situation",
    "i attracted them for a reason",
    "we were meant to cross paths",
    "they reflected my shadow to me",
    "the universe sent them",
)

GENUINE_INTEGRATION: tuple[str, ...] = (
    "still feeling",
    "still processing",
    "even though i know",
    "trying to accept but",
    "working on accepting",
    "i feel angry and also",
    "both are true",
    "complicated",
    "haven't fully",
    "still sitting with",
    "it's hard even though",
)

EXTERNAL_REPEAT_SIGNALS: tuple[str, ...] = (
    "people always",
    "they always",
    "everyone always",
    "he always",
    "she always",
    "people never",
    "they never",
    "no one ever",
    "nobody ever",
    "always happens to me",
    "keeps happening",
    "happens every time",
    "why does this keep",
    "why do people always",
    "same thing every time",
    "every relationship ends",
    "every job ends",
    "every time i try",
    "why do i always end up",
    "always end up with someone who",
    "i attract",
    "i seem to attract",
)

AVOIDANCE_SIGNALS: tuple[str, ...] = (
    "i don't say anything",
    "i dont say anything",
    "i let it go",
    "i just avoid it",
    "i don't bring it up",
    "i smile and say fine",
    "i say it's fine when it isn't",
    "i keep hoping it will resolve",
    "i don't want to deal with",
    "i go around it",
    "i change the subject",
    "i never confront",
    "builds up and explodes",
    "built up for so long",
)

PEOPLE_PLEASING_SIGNALS: tuple[str, ...] = (
    "can't say no",
    "cant say no",
    "always say yes",
    "go along with things",
    "people take advantage",
    "take advantage of me",
    "always give more than i get",
    "give more than i get",
    "i do so much and no one notices",
    "do so much and no one",
    "i put everyone else first",
    "put everyone else first",
    "hard to say no",
    "feel guilty saying no",
    "end up resenting",
    "i agree and then regret",
    "i sacrifice for everyone",
    "why do i always end up with people who take",
    "seem to say no",
    "cannot say no",
)

OVERTHINKING_SIGNALS: tuple[str, ...] = (
    "replay conversations",
    "go over it in my head",
    "can't stop thinking",
    "analyse everything",
    "think from every angle",
    "can't turn my brain off",
    "lie awake thinking",
    "overthink everything",
    "overthink things",
    "rehearse what i'm going to say",
    "over-analyse",
    "i think too much",
    "can't stop replaying",
    "my brain won't stop",
    "thinking in circles",
)

WITHDRAWAL_SIGNALS: tuple[str, ...] = (
    "go quiet",
    "shut down",
    "go cold",
    "disappear",
    "pull away",
    "go silent",
    "don't respond",
    "withdraw",
    "close off",
    "i just stop talking",
    "i leave conversations",
    "i go numb",
    "push people away when",
    "i isolate when",
)

PERFECTIONISM_SIGNALS: tuple[str, ...] = (
    "has to be perfect",
    "if it's not perfect",
    "if it is not perfect",
    "can't start until",
    "go over it again and again",
    "never good enough",
    "nothing is ever good enough",
    "people never meet my standards",
    "i'm the only one who does it right",
    "can't submit it",
    "not ready yet",
    "hard on myself",
    "impossible standards",
    "it has to be right",
    "i can't stop fixing",
)
