"""Static config for spiritual bypass and shadow-pattern detectors."""

from __future__ import annotations

BYPASS_DISMISS: tuple[str, ...] = (
    "everything happens for a reason",
    "it was meant to be",
    "the universe has a plan",
    "this is my karma",
    "i'm meant to learn from this",
    "it's all happening for my highest good",
    "i just need to let go",
    "i need to surrender",
    "i need to accept it",
    "i shouldn't be attached",
    "i need to raise my vibration",
    "this is just an ego reaction",
    "i need to transcend this",
    "at a soul level i chose this",
    "my higher self knows why",
    "i'm being tested",
    "this is a lesson i needed",
    "everything is perfect as it is",
    "i just need to be grateful",
)

PREMATURE_ACCEPTANCE: tuple[str, ...] = (
    "i've already forgiven them",
    "i'm at peace with it",
    "i've moved on",
    "i'm over it now",
    "i've accepted it",
    "i'm grateful for the lesson",
    "it made me stronger",
    "everything worked out for the best",
    "i'm not angry anymore",
    "i've released it",
)

SPIRITUAL_INFLATION: tuple[str, ...] = (
    "as a lightworker",
    "as an empath i feel",
    "i'm highly sensitive so",
    "my vibration is too high for",
    "i've ascended past",
    "from a 5d perspective",
    "i've done the work",
    "i'm very spiritually advanced",
    "most people can't understand",
    "i operate at a different level",
)

BYPASS_ACCOUNTABILITY: tuple[str, ...] = (
    "it was their karma not mine",
    "they were my teacher",
    "i called this into my life",
    "i manifested this situation",
    "i attracted them for a reason",
    "we were meant to cross paths",
    "they reflected my shadow to me",
    "the universe sent them",
)

GENUINE_INTEGRATION: tuple[str, ...] = (
    "still feeling",
    "still processing",
    "even though i know",
    "trying to accept but",
    "working on accepting",
    "i feel angry and also",
    "both are true",
    "complicated",
    "haven't fully",
    "still sitting with",
    "it's hard even though",
)

EXTERNAL_REPEAT_SIGNALS: tuple[str, ...] = (
    "people always",
    "they always",
    "everyone always",
    "he always",
    "she always",
    "people never",
    "they never",
    "no one ever",
    "nobody ever",
    "always happens to me",
    "keeps happening",
    "happens every time",
    "why does this keep",
    "why do people always",
    "same thing every time",
    "every relationship ends",
    "every job ends",
    "every time i try",
    "why do i always end up",
    "always end up with someone who",
    "i attract",
    "i seem to attract",
)

AVOIDANCE_SIGNALS: tuple[str, ...] = (
    "i don't say anything",
    "i dont say anything",
    "i let it go",
    "i just avoid it",
    "i don't bring it up",
    "i smile and say fine",
    "i say it's fine when it isn't",
    "i keep hoping it will resolve",
    "i don't want to deal with",
    "i go around it",
    "i change the subject",
    "i never confront",
    "builds up and explodes",
    "built up for so long",
)

PEOPLE_PLEASING_SIGNALS: tuple[str, ...] = (
    "can't say no",
    "cant say no",
    "always say yes",
    "go along with things",
    "people take advantage",
    "take advantage of me",
    "always give more than i get",
    "give more than i get",
    "i do so much and no one notices",
    "do so much and no one",
    "i put everyone else first",
    "put everyone else first",
    "hard to say no",
    "feel guilty saying no",
    "end up resenting",
    "i agree and then regret",
    "i sacrifice for everyone",
    "why do i always end up with people who take",
    "seem to say no",
    "cannot say no",
)

OVERTHINKING_SIGNALS: tuple[str, ...] = (
    "replay conversations",
    "go over it in my head",
    "can't stop thinking",
    "analyse everything",
    "think from every angle",
    "can't turn my brain off",
    "lie awake thinking",
    "overthink everything",
    "overthink things",
    "rehearse what i'm going to say",
    "over-analyse",
    "i think too much",
    "can't stop replaying",
    "my brain won't stop",
    "thinking in circles",
)

WITHDRAWAL_SIGNALS: tuple[str, ...] = (
    "go quiet",
    "shut down",
    "go cold",
    "disappear",
    "pull away",
    "go silent",
    "don't respond",
    "withdraw",
    "close off",
    "i just stop talking",
    "i leave conversations",
    "i go numb",
    "push people away when",
    "i isolate when",
)

PERFECTIONISM_SIGNALS: tuple[str, ...] = (
    "has to be perfect",
    "if it's not perfect",
    "if it is not perfect",
    "can't start until",
    "go over it again and again",
    "never good enough",
    "nothing is ever good enough",
    "people never meet my standards",
    "i'm the only one who does it right",
    "can't submit it",
    "not ready yet",
    "hard on myself",
    "impossible standards",
    "it has to be right",
    "i can't stop fixing",
)

# ---------------------------------------------------------------------------
# Ancestral / intergenerational pattern detector
# ---------------------------------------------------------------------------

ANCESTRAL_SIGNALS: tuple[str, ...] = (
    "just like my mother",
    "just like my father",
    "just like my parents",
    "same as my mother",
    "same as my father",
    "my mother was the same way",
    "my father was the same way",
    "this runs in my family",
    "runs in the family",
    "it goes back generations",
    "every woman in my family",
    "every man in my family",
    "the men in my family",
    "the women in my family",
    "we all do this",
    "my grandmother was like this",
    "my grandfather was like this",
    "i was raised to believe",
    "i was taught to",
    "in my family we never",
    "nobody in my family ever",
    "she couldn't give what she never had",
    "he couldn't give what he never had",
    "she was doing what she knew",
    "he was doing what he knew",
    "she was wounded too",
    "he was wounded too",
    "i grieve for what my mother",
    "i grieve for what my father",
    "inherited from",
    "passed down to me",
    "carried through generations",
    "intergenerational",
    "ancestral",
    "family pattern",
    "family wound",
    "mother wound",
    "father wound",
)

# ---------------------------------------------------------------------------
# Fear of visibility detector
# ---------------------------------------------------------------------------

VISIBILITY_FEAR_SIGNALS: tuple[str, ...] = (
    "afraid to post",
    "afraid to share",
    "afraid to put myself out there",
    "what if people judge me",
    "what if people see who i really am",
    "i can't let people see",
    "i hide this part of myself",
    "i shrink when people look at me",
    "i go invisible",
    "i want to say something but i hold back",
    "afraid of attention",
    "afraid of being noticed",
    "what if i'm wrong in public",
    "afraid to be wrong out loud",
    "i keep myself small",
    "i make myself smaller",
    "what if people see through me",
    "afraid to claim space",
    "i don't take up space",
    "i delete everything before i post",
    "i almost shared this but",
    "i almost posted but",
    "i hold back what i really think",
    "i don't want to be seen",
    "being visible feels dangerous",
    "being seen feels risky",
    "i disappear when people look at me",
    "i go quiet when i'm watched",
)

# ---------------------------------------------------------------------------
# Creative drought detector
# ---------------------------------------------------------------------------

CREATIVE_DROUGHT_SIGNALS: tuple[str, ...] = (
    "i don't know what to create anymore",
    "i used to know what to say",
    "the ideas have stopped coming",
    "nothing comes out",
    "i sit down to work and there's nothing",
    "i stare at the blank page",
    "i've lost my voice",
    "i don't know what i want to say",
    "i used to be able to write",
    "i used to be able to make",
    "i feel creatively empty",
    "i feel dried up",
    "nothing inspires me",
    "everything i make feels fake",
    "nothing feels authentic anymore",
    "i keep copying others",
    "i don't know what's original",
    "everything feels derivative",
    "i start things and abandon them",
    "i can't finish anything",
    "the source has gone quiet",
    "creative block",
    "writer's block",
    "no inspiration",
    "can't find inspiration",
    "lost my creativity",
    "lost my muse",
    "can't create",
    "nothing flows",
)

# ---------------------------------------------------------------------------
# Empath boundary detector
# ---------------------------------------------------------------------------

EMPATH_SIGNALS: tuple[str, ...] = (
    "i absorb everyone's emotions",
    "i feel what others feel",
    "i don't know which feelings are mine",
    "i can't tell if this is my emotion",
    "i walk into a room and feel the energy",
    "i feel drained after being with people",
    "i need a lot of alone time to recover",
    "people dump their emotions on me",
    "everyone comes to me with their problems",
    "i take on others' pain",
    "i feel responsible for other people's feelings",
    "i feel everything so deeply",
    "i'm too sensitive",
    "being in crowds overwhelms me",
    "i don't know where i end and they begin",
    "i feel guilty when i can't help someone",
    "i feel their pain as if it were mine",
    "i get exhausted by other people's energy",
    "i feel what my partner feels",
    "i feel what my mother feels",
    "i feel what my friend feels",
    "highly sensitive",
    "hsp",
    "empath",
    "picking up on energy",
    "absorbing energy",
    "energetically drained",
    "i carry everyone",
    "can't separate my feelings from",
)

# ---------------------------------------------------------------------------
# Perfectionism paralysis detector
# (extends PERFECTIONISM_SIGNALS already defined above in this file)
# ---------------------------------------------------------------------------

PERFECTIONISM_PARALYSIS_SIGNALS: tuple[str, ...] = (
    "i can't start until i know it's right",
    "i can't share until it's perfect",
    "i keep reworking the same thing",
    "i can never finish anything",
    "i almost sent it but",
    "i keep deleting and starting over",
    "i don't want to put it out there until it's ready",
    "it's never ready",
    "nothing is ever good enough",
    "i'm afraid of doing it wrong in front of people",
    "what if i release this and it's not my best",
    "i've been working on this for months and",
    "i keep waiting for the right moment",
    "waiting until i know more",
    "waiting until i'm ready",
    "i compare everything i make to",
    "i can't start because i don't know if i can do it well",
    "not ready to share",
    "not ready to release",
    "can't finish",
    "the finish line keeps moving",
    "i keep revising",
    "i'll do it when it's better",
    "i'll share it when",
    "not good enough to show",
    "afraid to commit to something that might fail",
)
