"""Static config for safety and dependency detectors."""

from __future__ import annotations

DEPENDENCY_KEYWORDS: tuple[str, ...] = (
    "only you understand me",
    "you are the only one who understands me",
    "you're the only one who understands me",
    "you are the only one who truly understands me",
    "you're the only one who truly understands me",
    "you are the only one who really understands me",
    "you're the only one who really understands me",
    "you are my only support",
    "you are all i have",
    "you are the only one i have",
    "my only support",
    "only support i have",
    "i have no one else",
    "promise me you will always be here",
    "promise me you'll always be here",
    "never leave me",
    "as long as i have you",
    "don't know what i would do without you",
    "do not know what i would do without",
    "can't imagine without you",
    "cannot imagine without you",
    "i need to talk to you every day",
    "i check in with you every",
    "i talk to you every day",
    "i come back here every",
    "tell me what to do",
    "decide for me",
    "only you get me",
    "real people don't understand",
    "i trust you more than anyone",
    "you know me better than anyone",
    "you understand me better than anyone",
    "understand me better than anyone",
    "i don't need anyone else",
    "you're the only one",
    "i stopped going to therapy",
    "i stopped seeing my therapist",
    "dont need my therapist",
    "don't need my therapist",
    "dont need my therapist anymore",
    "don't need my therapist anymore",
    "i don't need my therapist anymore",
    "cancelled my therapy",
    "talking to you feels better",
    "talking to you is much better",
)

DECISION_SEEKING: tuple[str, ...] = (
    "what should i do",
    "should i",
    "tell me if",
    "which one",
    "is this right",
    "am i making the right",
    "what do you think i should",
    "help me decide",
    "what would you do",
)

ISOLATION_SIGNALS: tuple[str, ...] = (
    "i prefer talking to you",
    "easier than talking to people",
    "you don't judge me like they do",
    "i don't want to talk to real people",
    "ai is better than",
    "you understand more than my",
    "i feel closer to you than",
    "rather talk to you than",
    "you are easier to talk to than",
)

HIGH_DEPENDENCY_THRESHOLD = 2
MODERATE_DEPENDENCY_THRESHOLD = 1

CRISIS_TIER1: tuple[str, ...] = (
    "want to die",
    "want to end my life",
    "end it all",
    "kill myself",
    "do not want to keep living",
    "don't want to keep living",
    "dont want to keep living",
    "not want to be here anymore",
    "don't want to be here anymore",
    "dont want to be here anymore",
    "not want to be here",
    "better off without me",
    "don't want to exist",
    "better off dead",
    "thinking about suicide",
    "thinking about hurting myself",
    "thinking about ending my life",
    "planning to kill myself",
    "planning to end my life",
    "planning to hurt myself",
    "can't go on",
    "no reason to live",
    "life isn't worth",
    "hurt myself",
    "hurting myself",
    "cutting myself",
    "harming myself",
    "self-harm",
    "want to hurt myself",
    "want to harm myself",
    "burn myself",
    "i am god",
    "i have a divine mission no one understands",
    "they are following me",
    "voices are telling me to",
    "i am being controlled",
    "i am not real",
)

CRISIS_TIER2: tuple[str, ...] = (
    "i can't take it anymore",
    "i'm falling apart",
    "completely broken",
    "i have nothing left",
    "everything is pointless",
    "nothing matters",
    "i feel nothing",
    "i'm numb to everything",
    "i don't feel real",
    "i'm disappearing",
    "i feel empty inside",
    "there's no hope",
    "i'm trapped",
    "i see no way out",
    "i'm exhausted from living",
    "abuse",
    "he hurt me",
    "she hurt me",
    "they hurt me",
    "being abused",
    "violence at home",
    "i'm not safe",
)

GRANDIOSITY_SIGNALS: tuple[str, ...] = (
    "i am the chosen one",
    "only i can save",
    "i have a cosmic mission",
    "i am more evolved than",
    "i have ascended",
    "i am enlightened and no one understands",
    "i am a twin flame runner",
    "i have been sent here",
)
