"""Generated by scripts/verify_soulmate_consumer_sync.py; do not edit."""

APPROVED_SOULMATE_SKILLS = (
    (
        "soulmate.foundation.contracts",
        "0.1.0",
        ">=0.1.0,<0.2.0",
        "foundation/contracts.md",
    ),
    (
        "soulmate.foundation.resource-boundaries",
        "0.1.0",
        ">=0.1.0,<0.2.0",
        "foundation/resource-boundaries.md",
    ),
    (
        "soulmate.foundation.knowledge-resolution",
        "0.1.0",
        ">=0.1.0,<0.2.0",
        "foundation/knowledge-resolution.md",
    ),
    (
        "soulmate.foundation.text-normalization",
        "0.1.0",
        ">=0.1.0,<0.2.0",
        "foundation/text-normalization.md",
    ),
    (
        "soulmate.foundation.data-validation",
        "0.1.0",
        ">=0.1.0,<0.2.0",
        "foundation/data-validation.md",
    ),
)
