// Atlas Nội Tâm: Document copy tách theo locale để các route công khai duy trì scope rõ ràng mà không phụ thuộc backend runtime.
import type { Locale } from "@/i18n";

export type DocumentKind = "how" | "boundaries" | "notes" | "download" | "privacy" | "faq";
type Section = { label: string; title: string; body: string };
type DocumentCopy = { eyebrow: string; title: string; lede: string; sections?: Section[]; faq?: [string, string][] };

const en: Record<DocumentKind, DocumentCopy> = {
  how: { eyebrow: "A usable sequence", title: "Start with what is present.", lede: "SoulMap is not a personality test or a one-size framework. It begins with lived territory, then chooses a bounded lens.", sections: [{ label: "01", title: "Notice the territory", body: "Name what is actually present before reaching for an explanation. Crisis and safety signals take priority over interpretation." }, { label: "02", title: "Choose one layer", body: "Use the narrowest layer that fits the moment. A lens is a way to look, not a label that fixes identity." }, { label: "03", title: "Return authorship", body: "Keep conclusions provisional and place meaning back with the person living the experience." }] },
  boundaries: { eyebrow: "Non-negotiable scope", title: "Clarity without false authority.", lede: "SoulMap uses careful language so reflection does not become diagnosis, prediction, or a replacement for human support.", sections: [{ label: "01", title: "No diagnosis", body: "Patterns can be explored as possibilities. They are not medical labels or conclusions about a person." }, { label: "02", title: "No prediction", body: "Symbols and frameworks never prove destiny, hidden status, or a guaranteed outcome." }, { label: "03", title: "No replacement", body: "A static skill bundle cannot replace crisis support, therapy, medical care, or trusted human relationships." }] },
  notes: { eyebrow: "Field notes", title: "Small observations, held lightly.", lede: "These notes describe the posture behind the framework, not rules for someone else’s life.", sections: [{ label: "01", title: "Mirror first", body: "A useful response lets the person recognize their own language before it introduces a theory." }, { label: "02", title: "Safety is not a tone", body: "Warmth cannot soften a boundary that is necessary for safety, consent, or reality testing." }, { label: "03", title: "The outside world matters", body: "A good close returns attention to ordinary life rather than suggesting the tool must continue the relationship." }] },
  download: { eyebrow: "Use with an AI host", title: "Import the knowledge, not a promise.", lede: "SoulMap and Soulmate ship as Markdown artifacts for compatible external AI tools. The site does not host an AI model.", sections: [{ label: "01", title: "Skill package", body: "Use the `.skill` package with tools that accept an importable skill bundle." }, { label: "02", title: "Knowledge archive", body: "Use the `.zip` archive with tools that accept Markdown knowledge files." }, { label: "03", title: "Before importing", body: "Read the artifact scope, provider terms, and source bundle before applying it in a conversation." }] },
  privacy: { eyebrow: "Privacy posture", title: "This site is intentionally quiet.", lede: "The public static surface is built to explain SoulMap, not to collect a personal reflective history.", sections: [{ label: "01", title: "Collection", body: "The static site does not provide account creation, private session storage, or a hosted chat service." }, { label: "02", title: "External providers", body: "If you open an external AI provider, that provider’s own terms and privacy practices apply." }, { label: "03", title: "Source visibility", body: "Raw public Markdown bundles are published for inspection. They do not contain a user’s private inputs." }] },
  faq: { eyebrow: "Practical answers", title: "Questions before you begin.", lede: "A short guide to what the public artifacts are for, and where their boundaries remain.", faq: [["What is SoulMap AI?", "A reflective framework and collection of importable Markdown skills for external AI hosts. It is not a hosted AI service."], ["Is SoulMap a therapist, doctor, or crisis service?", "No. It does not diagnose, provide treatment, or replace immediate support. Safety language takes priority whenever risk is present."], ["What are SoulMap Skills?", "They are structured Markdown layers that describe a bounded role, language, and source guidance for a compatible AI host."], ["How do I use a Skill with an AI tool?", "Open a raw bundle or import a published artifact into a compatible provider, then retain the provider’s own account and privacy context."], ["Does the website collect personal data?", "The static site has no account system or hosted conversation store. External provider activity is governed by that provider."], ["Why use careful language?", "The framework avoids turning metaphor, reflection, or a transient pattern into diagnosis, prediction, or authority."]] },
};

const vi: Record<DocumentKind, DocumentCopy> = {
  how: { eyebrow: "Một trình tự có thể dùng", title: "Bắt đầu từ điều đang hiện diện.", lede: "SoulMap không phải trắc nghiệm tính cách hay một khung dùng cho mọi người. Nó bắt đầu từ vùng đang sống, rồi chọn một lăng kính có ranh giới.", sections: [{ label: "01", title: "Nhận ra vùng đang sống", body: "Gọi tên điều thực sự đang hiện diện trước khi tìm một lời giải thích. Tín hiệu khủng hoảng và an toàn được ưu tiên hơn diễn giải." }, { label: "02", title: "Chọn một lớp", body: "Dùng lớp hẹp nhất phù hợp với khoảnh khắc. Lăng kính là cách nhìn, không phải nhãn cố định danh tính." }, { label: "03", title: "Trả quyền làm chủ", body: "Giữ kết luận ở dạng tạm thời và đặt ý nghĩa trở lại với người đang sống trải nghiệm đó." }] },
  boundaries: { eyebrow: "Phạm vi không thương lượng", title: "Rõ ràng mà không giả thẩm quyền.", lede: "SoulMap dùng ngôn ngữ cẩn trọng để phản chiếu không trở thành chẩn đoán, dự đoán hay thay thế hỗ trợ con người.", sections: [{ label: "01", title: "Không chẩn đoán", body: "Mô thức chỉ được xem như khả năng. Chúng không phải nhãn y khoa hay kết luận về một người." }, { label: "02", title: "Không dự đoán", body: "Biểu tượng và framework không bao giờ chứng minh định mệnh, vị thế ẩn hay một kết quả được bảo đảm." }, { label: "03", title: "Không thay thế", body: "Một gói Skill tĩnh không thể thay thế hỗ trợ khủng hoảng, trị liệu, chăm sóc y tế hay những mối quan hệ con người đáng tin cậy." }] },
  notes: { eyebrow: "Ghi chú thực địa", title: "Những quan sát nhỏ, giữ thật nhẹ.", lede: "Các ghi chú này mô tả tư thế phía sau framework, không phải quy tắc cho đời sống của người khác.", sections: [{ label: "01", title: "Tấm gương trước", body: "Một phản hồi hữu ích để người đó nhận ra ngôn ngữ của mình trước khi đưa vào một lý thuyết." }, { label: "02", title: "An toàn không phải giọng điệu", body: "Sự ấm áp không thể làm mềm một ranh giới cần thiết cho an toàn, sự đồng thuận hoặc kiểm chứng thực tế." }, { label: "03", title: "Đời sống bên ngoài quan trọng", body: "Một lời khép lại tốt đưa sự chú ý về đời thường thay vì gợi ý công cụ phải tiếp tục mối quan hệ." }] },
  download: { eyebrow: "Dùng với AI host", title: "Import tri thức, không import một lời hứa.", lede: "SoulMap và Soulmate được phát hành dưới dạng Markdown artifact cho các công cụ AI bên ngoài tương thích. Website không host mô hình AI.", sections: [{ label: "01", title: "Skill package", body: "Dùng gói `.skill` với công cụ chấp nhận skill bundle có thể import." }, { label: "02", title: "Knowledge archive", body: "Dùng archive `.zip` với công cụ chấp nhận các tệp kiến thức Markdown." }, { label: "03", title: "Trước khi import", body: "Đọc phạm vi artifact, điều khoản của nhà cung cấp và source bundle trước khi dùng trong hội thoại." }] },
  privacy: { eyebrow: "Tư thế riêng tư", title: "Bề mặt này được chủ đích giữ yên lặng.", lede: "Bề mặt tĩnh công khai được xây dựng để giải thích SoulMap, không để thu thập một lịch sử phản chiếu riêng tư.", sections: [{ label: "01", title: "Thu thập", body: "Website tĩnh không cung cấp tạo tài khoản, lưu phiên riêng tư hay dịch vụ chat được host." }, { label: "02", title: "Nhà cung cấp bên ngoài", body: "Nếu bạn mở một AI provider bên ngoài, điều khoản và thực hành riêng tư của provider đó sẽ được áp dụng." }, { label: "03", title: "Tính hiển thị của nguồn", body: "Raw Markdown bundle công khai được phát hành để kiểm tra. Chúng không chứa dữ liệu riêng tư của người dùng." }] },
  faq: { eyebrow: "Câu trả lời thực tế", title: "Câu hỏi trước khi bắt đầu.", lede: "Hướng dẫn ngắn về công dụng của artifact công khai và nơi các ranh giới vẫn được giữ.", faq: [["SoulMap AI là gì?", "Một framework phản chiếu và tập hợp Markdown skill có thể import cho AI host bên ngoài. Nó không phải dịch vụ AI được host."], ["SoulMap có phải là nhà trị liệu, bác sĩ hoặc dịch vụ khủng hoảng?", "Không. Nó không chẩn đoán, điều trị hay thay thế hỗ trợ tức thời. Ngôn ngữ an toàn được ưu tiên khi có rủi ro."], ["SoulMap Skills là gì?", "Chúng là các lớp Markdown có cấu trúc, mô tả vai trò có ranh giới, ngôn ngữ và hướng dẫn nguồn cho một AI host tương thích."], ["Dùng Skill với công cụ AI như thế nào?", "Mở raw bundle hoặc import artifact đã phát hành vào provider tương thích, đồng thời giữ ngữ cảnh tài khoản và riêng tư của chính provider đó."], ["Website có thu thập dữ liệu cá nhân không?", "Website tĩnh không có hệ thống tài khoản hoặc lưu hội thoại. Hoạt động trên provider ngoài tuân theo provider đó."], ["Vì sao dùng ngôn ngữ cẩn trọng?", "Framework tránh biến ẩn dụ, phản chiếu hay mô thức thoáng qua thành chẩn đoán, dự đoán hoặc thẩm quyền."]] },
};

const ko: Record<DocumentKind, DocumentCopy> = {
  how: { eyebrow: "사용 가능한 순서", title: "지금 있는 것에서 시작하세요.", lede: "SoulMap은 성격 검사나 모든 사람에게 적용되는 프레임워크가 아닙니다. 체험된 영역에서 시작해 경계가 있는 관점을 선택합니다.", sections: [{ label: "01", title: "영역 알아차리기", body: "설명에 도달하기 전에 실제로 존재하는 것을 이름 붙이세요. 위기와 안전 신호는 해석보다 우선합니다." }, { label: "02", title: "하나의 계층 고르기", body: "그 순간에 맞는 가장 좁은 계층을 사용하세요. 렌즈는 보는 방식이지 정체성을 고정하는 레이블이 아닙니다." }, { label: "03", title: "주도권 돌려주기", body: "결론은 잠정적으로 유지하고 의미를 경험을 사는 사람에게 되돌리세요." }] },
  boundaries: { eyebrow: "협상할 수 없는 범위", title: "가짜 권위 없는 명료함.", lede: "SoulMap은 성찰이 진단, 예측 또는 인간적 지원의 대체물이 되지 않도록 신중한 언어를 사용합니다.", sections: [{ label: "01", title: "진단하지 않기", body: "패턴은 가능성으로만 탐색할 수 있습니다. 의료적 레이블이나 한 사람에 대한 결론이 아닙니다." }, { label: "02", title: "예측하지 않기", body: "상징과 프레임워크는 운명, 숨은 지위, 보장된 결과를 증명하지 않습니다." }, { label: "03", title: "대체하지 않기", body: "정적 Skill bundle은 위기 지원, 치료, 의료 서비스 또는 신뢰할 수 있는 인간 관계를 대체할 수 없습니다." }] },
  notes: { eyebrow: "필드 노트", title: "작은 관찰을 가볍게 붙들기.", lede: "이 노트는 프레임워크 뒤의 자세를 설명하며, 다른 사람의 삶을 위한 규칙이 아닙니다.", sections: [{ label: "01", title: "거울이 먼저", body: "유용한 응답은 이론을 도입하기 전에 사람이 자기 언어를 알아차리게 합니다." }, { label: "02", title: "안전은 어조가 아닙니다", body: "따뜻함은 안전, 동의 또는 현실 검증에 필요한 경계를 부드럽게 만들 수 없습니다." }, { label: "03", title: "도구 밖의 삶이 중요합니다", body: "좋은 마무리는 도구가 관계를 계속해야 한다고 암시하지 않고 일상으로 주의를 돌립니다." }] },
  download: { eyebrow: "AI host와 함께 사용", title: "약속이 아니라 지식을 import하세요.", lede: "SoulMap과 Soulmate는 호환되는 외부 AI 도구를 위한 Markdown artifact로 제공됩니다. 웹사이트는 AI 모델을 host하지 않습니다.", sections: [{ label: "01", title: "Skill package", body: "import 가능한 skill bundle을 허용하는 도구에서 `.skill` 패키지를 사용하세요." }, { label: "02", title: "Knowledge archive", body: "Markdown 지식 파일을 받는 도구에서 `.zip` archive를 사용하세요." }, { label: "03", title: "Import 전에", body: "대화에 적용하기 전에 artifact 범위, provider 약관, source bundle을 읽으세요." }] },
  privacy: { eyebrow: "개인정보 자세", title: "이 표면은 의도적으로 조용합니다.", lede: "공개 static surface는 SoulMap을 설명하기 위한 것이지 개인 성찰 기록을 수집하기 위한 것이 아닙니다.", sections: [{ label: "01", title: "수집", body: "정적 사이트는 계정 생성, 개인 세션 저장 또는 host된 채팅 서비스를 제공하지 않습니다." }, { label: "02", title: "외부 provider", body: "외부 AI provider를 열면 해당 provider의 약관과 개인정보 보호 관행이 적용됩니다." }, { label: "03", title: "소스 공개", body: "공개 raw Markdown bundle은 검토를 위해 게시됩니다. 사용자 개인 입력을 포함하지 않습니다." }] },
  faq: { eyebrow: "실용적인 답변", title: "시작 전의 질문.", lede: "공개 artifact의 용도와 경계가 유지되는 지점을 위한 짧은 안내입니다.", faq: [["SoulMap AI란 무엇인가요?", "외부 AI host를 위한 성찰 프레임워크와 import 가능한 Markdown skill 모음입니다. host된 AI 서비스가 아닙니다."], ["SoulMap은 치료사, 의사 또는 위기 서비스인가요?", "아니요. 진단하거나 치료를 제공하거나 즉각적 지원을 대체하지 않습니다. 위험이 있을 때는 안전 언어가 우선합니다."], ["SoulMap Skills는 무엇인가요?", "호환 가능한 AI host를 위한 경계 있는 역할, 언어, 출처 지침을 설명하는 구조화된 Markdown 계층입니다."], ["AI 도구에서 Skill을 어떻게 사용하나요?", "raw bundle을 열거나 호환되는 provider에 공개 artifact를 import한 뒤 provider 자체의 계정과 개인정보 맥락을 유지하세요."], ["웹사이트가 개인 데이터를 수집하나요?", "정적 사이트에는 계정 시스템이나 host된 대화 저장소가 없습니다. 외부 provider 활동에는 해당 provider의 정책이 적용됩니다."], ["왜 신중한 언어를 사용하나요?", "프레임워크는 은유, 성찰 또는 일시적 패턴이 진단, 예측 또는 권위가 되는 것을 피합니다."]] },
};

export const documentCopy: Record<Locale, Record<DocumentKind, DocumentCopy>> = { en, vi, ko };
